version: '3'
services:
  mongodb:
    image: 'mongo'
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "3051:80"
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      # Mount everything but node_modules
      - /app/node_modules
      - ./server:/app
    environment:
      - MONGO_HOST=mongodb://mongodb
      - MONGO_DB=kumanote
      - MONGO_PORT=27017
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - 3000:3000