apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: api
          image: ythjkt/kumanote-api
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_HOST
              value: mongo-cluster-ip-service
            - name: MONGO_PORT
              value: '27017'
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongoauth
                  key: MONGO_USERNAME
            - name: MONOGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongoauth
                  key: MONGO_PASSWORD