apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ythjkt-com-tls
spec:
  secretName: kumanote-ythjkt-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kumanote.ythjkt.com
  dnsNames:
    - kumanote.ythjkt.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - kumanote.ythjkt.com